// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BookItem: typeof import('./components/book-item.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    IconEpFold: typeof import('~icons/ep/fold')['default']
    IconEpQuestionFilled: typeof import('~icons/ep/question-filled')['default']
    'IEpAdd-': typeof import('~icons/ep/add-')['default']
    IEpAddIcon: typeof import('~icons/ep/add-icon')['default']
    IEpAddLocation: typeof import('~icons/ep/add-location')['default']
    IEpArrowLeftBold: typeof import('~icons/ep/arrow-left-bold')['default']
    IEpArrowRightBold: typeof import('~icons/ep/arrow-right-bold')['default']
    IEpCircleCloseFilled: typeof import('~icons/ep/circle-close-filled')['default']
    IEpDocumentAdd: typeof import('~icons/ep/document-add')['default']
    'IEpEp:questionFilled': typeof import('~icons/ep/ep-question-filled')['default']
    IEpFold: typeof import('~icons/ep/fold')['default']
    IEpQuestionFilled: typeof import('~icons/ep/question-filled')['default']
    IEpQuestionilled: typeof import('~icons/ep/questionilled')['default']
    ReaderNav: typeof import('./components/reader-nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./components/test.vue')['default']
    Test2: typeof import('./components/test2.vue')['default']
    ThemeSwitch: typeof import('./components/theme-switch.vue')['default']
    Toolbar: typeof import('./components/toolbar.vue')['default']
    UniqueBookName: typeof import('./components/unique-book-name.vue')['default']
    UploadBook: typeof import('./components/upload-book.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
