// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdderSubtractor: typeof import('./components/adder-subtractor.vue')['default'];
    AddSub: typeof import('./components/add-sub.vue')['default'];
    BookItem: typeof import('./components/book-item.vue')['default'];
    ChangePage: typeof import('./components/toolbar/changePage.vue')['default'];
    ElAffix: typeof import('element-plus/es')['ElAffix'];
    ElAvatar: typeof import('element-plus/es')['ElAvatar'];
    ElBacktop: typeof import('element-plus/es')['ElBacktop'];
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox'];
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition'];
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker'];
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider'];
    ElDialog: typeof import('element-plus/es')['ElDialog'];
    ElDivider: typeof import('element-plus/es')['ElDivider'];
    ElEmpty: typeof import('element-plus/es')['ElEmpty'];
    ElIcon: typeof import('element-plus/es')['ElIcon'];
    ElInput: typeof import('element-plus/es')['ElInput'];
    ElOption: typeof import('element-plus/es')['ElOption'];
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar'];
    ElSelect: typeof import('element-plus/es')['ElSelect'];
    ElSlider: typeof import('element-plus/es')['ElSlider'];
    ElSwitch: typeof import('element-plus/es')['ElSwitch'];
    ElTooltip: typeof import('element-plus/es')['ElTooltip'];
    ElTree: typeof import('element-plus/es')['ElTree'];
    ElUpload: typeof import('element-plus/es')['ElUpload'];
    Fold: typeof import('./components/toolbar/fold.vue')['default'];
    IAntDesignFullscreenExitOutlined: typeof import('~icons/ant-design/fullscreen-exit-outlined')['default'];
    IAntDesignFullscreenOutlined: typeof import('~icons/ant-design/fullscreen-outlined')['default'];
    IAntDesignMenuOutlined: typeof import('~icons/ant-design/menu-outlined')['default'];
    IconEpFold: typeof import('~icons/ep/fold')['default'];
    IconEpQuestionFilled: typeof import('~icons/ep/question-filled')['default'];
    'IEpAdd-': typeof import('~icons/ep/add-')['default'];
    IEpAddIcon: typeof import('~icons/ep/add-icon')['default'];
    IEpAddLocation: typeof import('~icons/ep/add-location')['default'];
    IEpArrowLeftBold: typeof import('~icons/ep/arrow-left-bold')['default'];
    IEpArrowRightBold: typeof import('~icons/ep/arrow-right-bold')['default'];
    IEpCircleCloseFilled: typeof import('~icons/ep/circle-close-filled')['default'];
    IEpDocumentAdd: typeof import('~icons/ep/document-add')['default'];
    'IEpEp:questionFilled': typeof import('~icons/ep/ep-question-filled')['default'];
    IEpFold: typeof import('~icons/ep/fold')['default'];
    IEpFullScreen: typeof import('~icons/ep/full-screen')['default'];
    IEpGrid: typeof import('~icons/ep/grid')['default'];
    IEpQuestionFilled: typeof import('~icons/ep/question-filled')['default'];
    IEpQuestionilled: typeof import('~icons/ep/questionilled')['default'];
    ReaderNav: typeof import('./components/reader-nav.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    Test: typeof import('./components/test.vue')['default'];
    Test2: typeof import('./components/test2.vue')['default'];
    ThemeSwitch: typeof import('./components/theme-switch.vue')['default'];
    Toc: typeof import('./components/toc.vue')['default'];
    Toolbar: typeof import('./components/toolbar.vue')['default'];
    Toolbar2: typeof import('./components/toolbar/toolbar2.vue')['default'];
    UniqueBookName: typeof import('./components/unique-book-name.vue')['default'];
    UploadBook: typeof import('./components/upload-book.vue')['default'];
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective'];
  }
}
